language: node_js
node_js:
  - "6"
  - "8"
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libusb-1.0-0-dev
